# Generated by Django 5.0.6 on 2024-07-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onedealsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('verified', 'verified'), ('Rejected', 'Rejected')], default='pending', max_length=15),
        ),
    ]
