# Generated by Django 5.0.6 on 2024-07-11 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onedealsapp', '0006_property_is_approved_userupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='is_approved',
        ),
    ]
