# Generated by Django 5.0.6 on 2024-07-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onedealsapp', '0012_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='status',
            field=models.CharField(choices=[('unread', 'unread'), ('viewed', 'viewed')], default='unread', max_length=15),
        ),
    ]
