# Generated by Django 5.0.6 on 2024-07-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onedealsapp', '0013_selection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='city',
            field=models.CharField(choices=[('', 'Select city'), ('14', 'Kazarkode'), ('13', 'Kannur'), ('12', 'wayanadu'), ('11', 'Kozhikode'), ('10', 'Malappuram'), ('09', 'Palakkad'), ('08', 'Thrissur'), ('07', 'Ernakulam'), ('06', 'Idukki'), ('05', 'Alappuzha'), ('04', 'Kottayam'), ('03', 'Pathanamthitta'), ('02', 'Kollam'), ('01', 'Thiruvananthapuram')], max_length=2),
        ),
    ]
