# Generated by Django 5.0.6 on 2024-07-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onedealsapp', '0018_property_custom_id_alter_property_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='pro_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='pro_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
