# Generated by Django 5.0.6 on 2024-07-24 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onedealsapp', '0019_contact_pro_id_enquiry_pro_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimo',
            old_name='description',
            new_name='caption',
        ),
        migrations.RemoveField(
            model_name='testimo',
            name='job',
        ),
    ]
